version: 1
disable_existing_loggers: True

formatters:
  default:
    format: 'date: {asctime} - {name} - {funcName} - {lineno} - {message}'
    style: '{'

handlers:
  default:
    class: logging.StreamHandler
    formatter: default
    level: DEBUG
  stderr:
    class: logging.StreamHandler
    formatter: default
    level: DEBUG

loggers:
  main:
    level: WARNING
    handlers: [default]
  graph_cell:
    level: WARNING
    handlers: [stderr]
  bfs:
    level: WARNING
    handlers: [default]

root:
  formatter: default
  handlers: [default]
  level: DEBUG

